# Generated by Django 4.1.6 on 2023-03-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinput',
        ),
    ]
