# Generated by Django 4.1.6 on 2023-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='operatingmargin',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='operatingprofit',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='priceperunit',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='unitssold',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinput',
            name='city',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='method',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='product',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='region',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='retailer',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='state',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
