# Generated by Django 4.1.6 on 2023-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_userinput_operatingmargin_userinput_operatingprofit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='operatingmargin',
            field=models.FloatField(),
        ),
    ]
